# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test 
     name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        // for loop with continue statement
for (int i = 1; i <= 10; i++) {
  // if i is even, skip the current iteration
  if (i % 2 == 0) {
    continue;
  }
  // print i
  System.out.println(i);
}
// while loop with continue statement
// declare an array of numbers
int[] numbers = {1, -2, 3, -4, 5, -6, 7, -8, 9, -10};
// declare an index variable
int i = 0;
// while loop condition
while (i < numbers.length) {
  // get the current number
  int number = numbers[i];
  // increment the index
  i++;
  // if number is negative, skip the current iteration
  if (number < 0) {
    continue;
  }
  // print number
  System.out.println(number);
}



        
